/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ligadefutbol;

import java.sql.Blob;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Alejandro
 */
public class ListaJugadoresPanel extends javax.swing.JPanel {

    private DefaultTableModel modeloTabla; 
    GestionJugador gestion = new GestionJugador();
    Blob foto;
    
    public ListaJugadoresPanel() {
        Conexion.conectar("localhost","root","");
        initComponents();
        if (!java.beans.Beans.isDesignTime()) {
        this.CargarDatosJTable();
        }
    }
    
    void CargarDatosJTable() {
        
        ArrayList<Jugador> listaJugadores = new ArrayList();
         
        modeloTabla = new DefaultTableModel() {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }                
        };
        jTable2.setModel(modeloTabla);

        //Rellenar las cabeceras de las columnas
        String[] cabecera = {"Id_jugador", "Nombre Completo", "Nombre Camiseta", "Numero Camiseta", "Edad"
        , "Equipo", "Posicion"};
        modeloTabla.setColumnIdentifiers(cabecera);

        listaJugadores = gestion.list();
        //Recorrer la lista de contactos para añadir algunos datos en el JTable
        for (Jugador jugador :listaJugadores) {
            //Se va mostrar sólo el nombre y los apellidos
            String[] datosFilaJugador = {
                String.valueOf(jugador.getId_jugador()), 
                jugador.getNombreApellidos(), 
                jugador.getNombreCamiseta(),
                String.valueOf(jugador.getNumeroCamisteta()),
                String.valueOf(jugador.getEdad()),
                jugador.getEquipo(),
                jugador.getPosicion()};
            modeloTabla.addRow(datosFilaJugador);
        }        

        //Establecer que sólo se pueda seleccionar una fila
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        //Ocultar columna de idContacto
        TableColumn tc = jTable2.getColumn("Id_jugador");
        jTable2.removeColumn(tc);
        
        //Mostrar vacíos los datos de contacto
        //mostrarDatosContacto();        
    }
//    void mostrarDatosContacto() {
//        //Obtener número de fila seleccionada en el JTable
//        int numFilaSelec = jTable1.getSelectedRow();
//        //Comprobar que el usuario ha seleccionado alguna fila
//        if(numFilaSelec!=-1) {
//            //Obtener el contacto correspondiente a la fila seleccionada
//            Jugador jugador = BDAgenda.leerContacto(
//                    Integer.valueOf((String)modeloTabla.getValueAt(numFilaSelec, 0)));
//            jLabelNombre.setText(contacto.getNombre());
//            jLabelApellidos.setText(contacto.getApellidos());
//            jLabelTelefono.setText(contacto.getTelefono());
//            jLabelCorreo.setText(contacto.getCorreo());            
//        } else {
//            jLabelNombre.setText("");
//            jLabelApellidos.setText("");
//            jLabelTelefono.setText("");
//            jLabelCorreo.setText("");
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
